apiVersion: v1
kind: Service
metadata:
  name: kube-rest-gateway
  labels:
    app: kube-rest-gateway
spec:
  selector:
    app: kube-rest-gateway
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30081
  type: NodePort