apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-rest-gateway
  namespace: argocd
spec:
  project: alpha-nemoclaw-project
  source:
    repoURL: https://github.com/alphanemoclaw/alpha_kube-rest-gateway.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: alpha-nemoclaw-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true